### PR TITLE
Fix the web interface & update the Dockerfile

### PR DESCRIPTION
**Pull request by p00rt**
hey, the web interface was throwing a 500 because some paths were wrong. 
I built the image with the new `Dockerfile`, which can be seen here: https://hub.docker.com/layers/kn0fl00k/botamusique/0.0.3-ytdlp2023.07.06/images/sha256-b579b03afd76f2d81f7bc3f56ad34654ed9d6c2de6a45a5b4390beab295436a5?context=explore

### CODE REVIEW

**Comment by azlux** [comment]
Any reason you've move the template into web/template ?

**Comment by p00rt** [comment]
they were in `web/templates` already, i just updated the paths to match the situation

**Comment by azlux** [comment]
> Dockerfile:14
> --
> ERROR: failed to solve: node:14-bullseye-slim: no match for platform in manifest: not found

The build have failed because node14 don't support arm 32bits (rasberry 2B) anymore.
I will check that

**Comment by azlux** [comment]
pymumble isn't install on the final docker image, will check that tomorrow

**Pull request merged**
