### PR TITLE
Migrate to modern JavaScript practices

### PR DESCRIPTION
**Pull request by TylerVigario**
## Current Checklist
- [x] Playlist loading
- [x] Library loading
- [x] Adding media (upload, URL, radio)
- [x] Playlist controls (play/pause, stop, next, etc.)
- [x] Library controls (add to playlist, download, delete, etc.)
- [ ] Loading state (progress indicator) for library, playlist, etc.

## Overall Goals
* Migrate to modern JavaScript practices
* Segregate code into Modules
* Remove internal jQuery usage
* Improve readability
* Improve performance

## Deadline
I hope to have this working and ready-to-merge by December 12th, 2020.

## Notes
* Contributes progress towards #157
* Would benefit from #236
* _The checklist is mostly for me at the moment lol_

### CODE REVIEW

**Comment by TerryGeng** [comment]
Hi! Finally see someone decided to refactor our web interface frontend 👍 
I think I need to apologize first because I was surely a novice in doing javascript and the codebase now looks like a dangerous swamp. Things tangle together in a mysterious way and it makes maintaining a horrible experience...

Looking forward to the "fresh" codebase this PR would bring, My best wishes to you!

**Comment by TerryGeng** [comment]
My latest PR addressed the thumbnail images. However, it did break the playlist display. I would leave this to you.

**Comment by TylerVigario** [comment]
@TerryGeng No worries, I'll get it fixed up tomorrow. Thanks for your help!

**Comment by azlux** [comment]
Why did you closed this PR ? You want to open a new one ?

**Pull request closed without merging**
