### PR TITLE
Allow opt-out to fetching changelogs on updates

### PR DESCRIPTION
**Pull request by mweinelt**
Fixes: #268

### CODE REVIEW

**Comment by TerryGeng** [comment]
Hi. Thanks for your PR.

Personally speaking, I would not create a new config option just to disable the changelog... What do you think about disable changelog fetching when `auto_check_update` is set to false?

**Comment by mweinelt** [comment]
Also possible, although less precise. I don't mind either way, you and @azlux decide.

**Comment by azlux** [comment]
I've an idea, can both configurations can be merge into a `offline` configuration ?
This will disable any update and changelog .

**Comment by mweinelt** [comment]
Which is odd, given that we can probably still play streams, even while `offline` is set.

**Comment by mweinelt** [comment]
I have updated the logic to not introduce an extra option but instead post the changelog only if automatic updates are enabled.

**Comment by TerryGeng** [comment]
LGTM. Thanks for your PR!

**Pull request merged**
