### PR TITLE
Don't show how to resume if playlist is empty when "when_nobody_in_channel = pause"

### PR DESCRIPTION
**Pull request by SeerLite**
That way there's no spam when the bot doesn't even have anything to play

### CODE REVIEW

**Comment by TerryGeng** [comment]
Thanks for the PR. Your idea makes sense to me. However, once the bot is paused, adding new songs won't automatically make it play.

In some cases, when the playlist is empty, once people leave the channel, the bot pauses itself. However, when people join back, they will feel annoying to see adding new songs does not work and they need to send `!play` manually to resume.

I think the best way to address this issue is, on the basis of your current commit, to add something to prevent the bot to pause when all people leave the channel if the playlist is empty.

Do you agree? :)

**Comment by SeerLite** [comment]
> However, once the bot is paused, adding new songs won't automatically make it play.

Whoops, I hadn't tested this and was sure it did. Is there a way to make it do it? I think that would be more intuitive. It's also how most Discord bots I've used operate.
That way we could also get rid of the "use !play" tip entirely. You'll immediately realize there's already a song in the queue when trying to add a new one, because it'll resume from the middle (or wherever it paused).

In the meantime I'm gonna make it not pause if it's empty in the first place.

I also noticed the bot spams the channel a lot anyway if there's movement **outside** the channel. Looks like the bot listens for all user movement across the whole server instead of just in its own channel. I could store the current channel's user list in an attribute and then check if the members **inside** the channel changed before starting `users_changed()`. ...Or I could just make the bot auto-play when adding new songs like I said above, and getting rid of the message entirely.

What do you think?

**Comment by azlux** [comment]
What do you mean by " the bot spams the channel a lot anyway if there's movement outside the channel" ?
What kind of message do you have ? do you mean logs ? The bot don't send messages on user movements.

**Comment by SeerLite** [comment]
No no, not logs. I meant the same message that this PR addresses.

* `users_changed()` is called on every user movement (on the whole server).
* It checks if the current room has 2 members.
* If it does, sends the help message: "Use !play to resume music!".

So if it's only the bot and someone else and there's movement outside the room, the bot is gonna send that help message even if nothing changed.
So yeah I should have been more specific. It doesn't spam all the time, but only when it's just the bot + someone else. Sorry for the confusion :s

**Comment by azlux** [comment]
Ok, I see the issue: this code is called : https://github.com/azlux/botamusique/blob/e079f948bcf07ff40fb392b7da671fb111331abe/mumbleBot.py#L350
I will add a check to avoid this issue.

**Comment by TerryGeng** [comment]
> Whoops, I hadn't tested this and was sure it did. Is there a way to make it do it? I think that would be more intuitive. It's also how most Discord bots I've used operate.
> That way we could also get rid of the "use !play" tip entirely. You'll immediately realize there's already a song in the queue when trying to add a new one, because it'll resume from the middle (or wherever it paused).

There has been discussion about this "feature", please refer to https://github.com/azlux/botamusique/issues/185#issuecomment-655826836.

I don't think I will going to change the behavior of how `!stop` and `!pause` works. I think, regarding this PR only, the best way to avoid the situation I explained is to avoid pausing when the playlist is empty.

**Comment by SeerLite** [comment]
> I don't think I will going to change the behavior of how !stop and !pause works. I think, regarding this PR only, the best way to avoid the situation I explained is to avoid pausing when the playlist is empty.

Alright I understand! I made the changes, should be good now. Sorry for the amount of pushes, I got confused for a second

**Comment by TerryGeng** [comment]
LGTM:).

Thanks for your contribution!

**Pull request merged**
