### PR TITLE
For URLItems: clone title into keywords, allows searching

### PR DESCRIPTION
**Pull request by Gunzinger**
This change copies the title into the keywords so youtube videos become searchable through the webinterface.
If a more elegant feature like searching by title is easily possible, that could be interesting to.
Ideally I would like to extend this later on by also adding the youtube channel name of the uploader into the keywords.

### CODE REVIEW

**Comment by Gunzinger** [comment]
I should note that this only applies to clips added after this code is included.
Some kind of one-shot trigger to update the database values for all "url" type files would be needed to adjust the existing data, is there a way to include/apply a one-shot execution of an SQL statement on a version upgrade?

**Comment by TerryGeng** [comment]
Thanks! This is my bad. If necessary, I can create an individual update function that updates the database between different versions.

I tried some in https://github.com/azlux/botamusique/blob/170389ea7c7bdbfae718227173450d483a415ed4/database.py#L354-L375

But this is actually not a good practice. I think we should keep a list of function that updates the database given the version number. Like one function that updates MUSIC_DATABASE_VERSION from 0 to 1, one function updates it from 1 to 2.

Leave this part for me. I will implement this soon.

**Comment by TerryGeng** [comment]
Done. You can have a test now :)

**Comment by Gunzinger** [comment]
Thank you for the fast action again!
Works perfectly, I have tested it on the existing old database and it is modified as expected for all existing entries that do not yet have keywords.
Due to this the search now works on everything too 👍

**Pull request merged**
