### PR TITLE
Add Popper.js link in HTML

### PR DESCRIPTION
**Pull request by TylerVigario**
Forgot to add the link in HTML so popovers are broken. This fixes that.

### CODE REVIEW

**Comment by TerryGeng** [comment]
I think I will merge all of these things after you have settled everything. Good luck!

**Comment by TylerVigario** [comment]
> I think I will merge all of these things after you have settled everything. Good luck!

I am not quite sure how to interpret that? This PR addresses the fact that popovers are broken RN.

**Comment by TerryGeng** [comment]
I don't usually use squash merge since it will create a huge commit and wipe out all history in the middle. But surely I will try to use "rebase" as possible as I can to avoid annoying "merge" commits.

**Comment by TylerVigario** [comment]
Rebase is nice but I typically set up my additions in a feature branch on my fork which should be squash merged in to reduce the number of commits that show up in the master branch. Anything that is significant should be listed in the actual PR which will show up in the merge.

**Pull request merged**
