### PR TITLE
Small improvements and virtualenvs

### PR DESCRIPTION
**Pull request by Lartza**
Language improvements, a gitignore file and tiny code improvements.

In addition change the installation instructions to use a virtualenv instead of wrecking havoc on the system root.

### CODE REVIEW

**Comment by azlux** [comment]
I will trust you on this one. I've never used virtualenv.

**Comment by Lartza** [comment]
With the two small corrections (python3 and the requirement of wheel under the venv) I got botamusique to run and play a youtube video just fine on "Ubuntu on Windows 10"

People should never use sudo pip and getting all of the requirements from the repos is not sensible on older distros so these instructions should be fine for anyone who isn't advanced enough to get botamusique running on their own.

**Comment by azlux** [comment]
Thank.
I will try this evening on my raspberry before merging.

**Comment by azlux** [comment]
conflicts ? I've merge #14 before #13 .....

**Pull request merged**
