### PR TITLE
fix: Racing condition happens when editing playlist. 

### LINKED ISSUE #279: IndexError when track wasn't added because length too long
**Describe the bug**
We have an empty playlist and try to add a youtube url that is above our configured limit of 180 minutes, the bot subsequently crashes with an `IndexError`.

```
[18:15:01] (Channel) $user: !url https://www.youtube.com/watch?v=7AOOhgLN3oY
[18:15:02] (Channel) musique.lossy.network: Download of https://www.youtube.com/watch?v=7AOOhgLN3oY in progress...
[18:15:03] (Channel) musique.lossy.network: Best of Starbucks Cafe Music Collection - 3 Hours of Smooth Jazz Piano is too long (3:16:47 > 3:00:00), removed from playlist!
[18:15:03] musique.lossy.network left channel and disconnected.
```

This only happens when the playlist is empty.

**Affected version**
33a9e75ba9d0a382f7a76d23a0ceb626924a8b49

**To Reproduce**
1. Clear the playlist
2. Add an item that is too long
3. Observe the bot erroring out

**Expected behavior**
Use for each loops instead of using explicit iterators.

**Additional context**
```pytb
[youtube] 7AOOhgLN3oY: Downloading webpage
[youtube] Downloading just video 7AOOhgLN3oY because of --no-playlist
[May 22 18:15:03 INFO] url: https://www.youtube.com/watch?v=7AOOhgLN3oY has a duration of 196.78333333333333 min -- too long
[May 22 18:15:03 INFO] url: fetching metadata of url https://www.youtube.com/watch?v=7AOOhgLN3oY
[youtube] 7AOOhgLN3oY: Downloading webpage
Traceback (most recent call last):
  File "/nix/store/vvlrp87i77yd9jm6fk4l69fm6mmj0pla-botamusique-unstable-2021-05-16/share/botamusique/.mumbleBot.py-wrapped", line 900, in <module>
    var.bot.loop()
  File "/nix/store/vvlrp87i77yd9jm6fk4l69fm6mmj0pla-botamusique-unstable-2021-05-16/share/botamusique/.mumbleBot.py-wrapped", line 554, in loop
    current = var.playlist.current_item()
  File "/nix/store/vvlrp87i77yd9jm6fk4l69fm6mmj0pla-botamusique-unstable-2021-05-16/share/botamusique/media/playlist.py", line 267, in current_item
    return self[self.current_index]
IndexError: list index out of range
```

### PR DESCRIPTION
**Pull request by TerryGeng**
Should fix #279.

### CODE REVIEW

**Comment by mweinelt** [comment]
With [`f139b65` (#280)](https://github.com/azlux/botamusique/pull/280/commits/f139b6552dbbaa98006bf89d5a582f7a5b5f646a) applied the issue is still reproducible.

```
May 23 16:47:41 juno botamusique[22408]: [2021-05-23 16:47:41,739] > [Thread-14] > [.mumbleBot.py-wrapped:265] bot: received command "url" with arguments "https://www.youtube.com/watch?v=7AOOhgLN3oY" from hexa-
May 23 16:47:41 juno botamusique[22408]: [2021-05-23 16:47:41,821] > [MainThread] > [.mumbleBot.py-wrapped:537] bot: next into the song: [url]  (https://www.youtube.com/watch?v=7AOOhgLN3oY)
May 23 16:47:41 juno botamusique[22408]: [2021-05-23 16:47:41,822] > [MainThread] > [.mumbleBot.py-wrapped:436] bot: current music isn't ready, start downloading.
May 23 16:47:41 juno botamusique[22408]: [2021-05-23 16:47:41,823] > [MainThread] > [.mumbleBot.py-wrapped:429] bot: start preparing item in thread: [url]  (https://www.youtube.com/watch?v=7AOOhgLN3oY)
May 23 16:47:41 juno botamusique[22408]: [2021-05-23 16:47:41,826] > [Prepare-e276d08] > [url.py:128] url: fetching metadata of url https://www.youtube.com/watch?v=7AOOhgLN3oY
May 23 16:47:41 juno botamusique[22408]: [2021-05-23 16:47:41,863] > [Validating] > [playlist.py:245] playlist: start validating...
May 23 16:47:41 juno botamusique[22408]: [2021-05-23 16:47:41,864] > [Validating] > [playlist.py:258] playlist: validating [url]  (https://www.youtube.com/watch?v=7AOOhgLN3oY)
May 23 16:47:41 juno botamusique[22408]: [2021-05-23 16:47:41,864] > [Thread-14] > [command.py:398] cmd: add to playlist: [url]  (https://www.youtube.com/watch?v=7AOOhgLN3oY)
May 23 16:47:42 juno botamusique[22408]: [youtube] 7AOOhgLN3oY: Downloading webpage
May 23 16:47:42 juno botamusique[22408]: len: 1, idx: 0
May 23 16:47:42 juno botamusique[22408]: len: 1, idx: 0
May 23 16:47:42 juno botamusique[22408]: len: 1, idx: 0
May 23 16:47:42 juno botamusique[22408]: len: 1, idx: 0
May 23 16:47:42 juno botamusique[22408]: len: 1, idx: 0
May 23 16:47:42 juno botamusique[22408]: len: 1, idx: 0
May 23 16:47:42 juno botamusique[22408]: len: 1, idx: 0
May 23 16:47:42 juno botamusique[22408]: [youtube] Downloading just video 7AOOhgLN3oY because of --no-playlist
May 23 16:47:42 juno botamusique[22408]: len: 1, idx: 0
May 23 16:47:42 juno botamusique[22408]: len: 1, idx: 0
May 23 16:47:42 juno botamusique[22408]: len: 1, idx: 0
May 23 16:47:42 juno botamusique[22408]: len: 1, idx: 0
May 23 16:47:43 juno botamusique[22408]: 2a00:e67:1fd:a:dcc6:1168:80d2:1ee2 - - [23/May/2021 16:47:43] "POST /post HTTP/1.1" 200 -
May 23 16:47:43 juno botamusique[22408]: [2021-05-23 16:47:43,155] > [Prepare-e276d08] > [url.py:106] url: https://www.youtube.com/watch?v=7AOOhgLN3oY has a duration of 196.78333333333333 min -- too long
May 23 16:47:43 juno botamusique[22408]: [2021-05-23 16:47:43,157] > [Validating] > [url.py:128] url: fetching metadata of url https://www.youtube.com/watch?v=7AOOhgLN3oY
May 23 16:47:43 juno botamusique[22408]: [2021-05-23 16:47:43,168] > [Prepare-e276d08] > [cache.py:104] library: cache freed for item: [url] Best of Starbucks Cafe Music Collection - 3 Hours of Smooth Jazz Piano (https://www.youtube.com/watch?v=7AOOhgLN3oY)
May 23 16:47:43 juno botamusique[22408]: [youtube] 7AOOhgLN3oY: Downloading webpage
May 23 16:47:43 juno botamusique[22408]: len: 1, idx: 0
May 23 16:47:43 juno botamusique[22408]: len: 1, idx: 0
May 23 16:47:43 juno botamusique[22408]: len: 0, idx: 0
May 23 16:47:43 juno botamusique[22408]: Traceback (most recent call last):
May 23 16:47:43 juno botamusique[22408]:   File "/nix/store/rqvvypa8c1y26sbfh083dsd02w4jsyvw-botamusique-unstable-2021-05-16/share/botamusique/.mumbleBot.py-wrapped", line 900, in <module>
May 23 16:47:43 juno botamusique[22408]:     var.bot.loop()
May 23 16:47:43 juno botamusique[22408]:   File "/nix/store/rqvvypa8c1y26sbfh083dsd02w4jsyvw-botamusique-unstable-2021-05-16/share/botamusique/.mumbleBot.py-wrapped", line 554, in loop
May 23 16:47:43 juno botamusique[22408]:     current = var.playlist.current_item()
May 23 16:47:43 juno botamusique[22408]:   File "/nix/store/rqvvypa8c1y26sbfh083dsd02w4jsyvw-botamusique-unstable-2021-05-16/share/botamusique/media/playlist.py", line 290, in current_item
May 23 16:47:43 juno botamusique[22408]:     return self[self.current_index]
May 23 16:47:43 juno botamusique[22408]: IndexError: list index out of range
May 23 16:47:43 juno systemd[1]: botamusique.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by TerryGeng** [comment]
Sorry, the previous commit was incomplete. I have re-pushed a new one. Would you please try again?

**Comment by mweinelt** [comment]
```
May 23 17:20:27 juno botamusique[23675]: [2021-05-23 17:20:27,504] > [Thread-93] > [.mumbleBot.py-wrapped:265] bot: received command "url" with arguments "https://www.youtube.com/watch?v=7AOOhgLN3oY" from hexa-
May 23 17:20:27 juno botamusique[23675]: [2021-05-23 17:20:27,530] > [MainThread] > [.mumbleBot.py-wrapped:537] bot: next into the song: [url]  (https://www.youtube.com/watch?v=7AOOhgLN3oY)
May 23 17:20:27 juno botamusique[23675]: [2021-05-23 17:20:27,531] > [MainThread] > [.mumbleBot.py-wrapped:436] bot: current music isn't ready, start downloading.
May 23 17:20:27 juno botamusique[23675]: [2021-05-23 17:20:27,531] > [MainThread] > [.mumbleBot.py-wrapped:429] bot: start preparing item in thread: [url]  (https://www.youtube.com/watch?v=7AOOhgLN3oY)
May 23 17:20:27 juno botamusique[23675]: [2021-05-23 17:20:27,539] > [Prepare-e276d08] > [url.py:128] url: fetching metadata of url https://www.youtube.com/watch?v=7AOOhgLN3oY
May 23 17:20:27 juno botamusique[23675]: [youtube] 7AOOhgLN3oY: Downloading webpage
May 23 17:20:27 juno botamusique[23675]: [2021-05-23 17:20:27,612] > [Validating] > [playlist.py:245] playlist: start validating...
May 23 17:20:27 juno botamusique[23675]: [2021-05-23 17:20:27,612] > [Thread-93] > [command.py:398] cmd: add to playlist: [url]  (https://www.youtube.com/watch?v=7AOOhgLN3oY)
May 23 17:20:27 juno botamusique[23675]: [2021-05-23 17:20:27,613] > [Validating] > [playlist.py:258] playlist: validating [url]  (https://www.youtube.com/watch?v=7AOOhgLN3oY)
May 23 17:20:28 juno botamusique[23675]: [youtube] Downloading just video 7AOOhgLN3oY because of --no-playlist
May 23 17:20:28 juno botamusique[23675]: [2021-05-23 17:20:28,158] > [Prepare-e276d08] > [url.py:106] url: https://www.youtube.com/watch?v=7AOOhgLN3oY has a duration of 196.78333333333333 min -- too long
May 23 17:20:28 juno systemd[1]: botamusique.service: Main process exited, code=exited, status=1/FAILURE
May 23 17:20:29 juno botamusique[23675]: [2021-05-23 17:20:28,159] > [Validating] > [url.py:128] url: fetching metadata of url https://www.youtube.com/watch?v=7AOOhgLN3oY
May 23 17:20:29 juno botamusique[23675]: [2021-05-23 17:20:28,172] > [Prepare-e276d08] > [cache.py:104] library: cache freed for item: [url] Best of Starbucks Cafe Music Collection - 3 Hours of Smooth Jazz Piano (https://www.youtube.com/watch?v=7AOOhgLN3oY)
May 23 17:20:29 juno botamusique[23675]: [youtube] 7AOOhgLN3oY: Downloading webpage
May 23 17:20:29 juno botamusique[23675]: Traceback (most recent call last):
May 23 17:20:29 juno botamusique[23675]:   File "/nix/store/wf67xd1b3lvsf007bnnlp7w5w8x37h19-botamusique-unstable-2021-05-16/share/botamusique/.mumbleBot.py-wrapped", line 900, in <module>
May 23 17:20:29 juno botamusique[23675]:     var.bot.loop()
May 23 17:20:29 juno botamusique[23675]:   File "/nix/store/wf67xd1b3lvsf007bnnlp7w5w8x37h19-botamusique-unstable-2021-05-16/share/botamusique/.mumbleBot.py-wrapped", line 554, in loop
May 23 17:20:29 juno botamusique[23675]:     current = var.playlist.current_item()
May 23 17:20:29 juno botamusique[23675]:   File "/nix/store/wf67xd1b3lvsf007bnnlp7w5w8x37h19-botamusique-unstable-2021-05-16/share/botamusique/media/playlist.py", line 289, in current_item
May 23 17:20:29 juno botamusique[23675]:     return self[self.current_index]
May 23 17:20:29 juno botamusique[23675]: IndexError: list index out of range
May 23 17:20:28 juno systemd[1]: botamusique.service: Failed with result 'exit-code'.
```

**Comment by TerryGeng** [comment]
Re-pushed. Give it a shot?

**Pull request merged**
