### PR TITLE
Further improvements to web interface

### PR DESCRIPTION
**Pull request by TylerVigario**
This PR again aims to address mobile styling (responsiveness) and further improve and simplify the web interface.

### CODE REVIEW

**Comment by TerryGeng** [comment]
Brilliant work! Looking forward to more great news from you ;)

**Comment by TylerVigario** [comment]
@TerryGeng Is library pagination working for you?

**Comment by TylerVigario** [comment]
Seeing as I'll be busy till next week this can be merged.

I want to address the next sections separately anyways.

**Comment by TerryGeng** [comment]
> @TerryGeng Is library pagination working for you?

It does for me.

**Pull request merged**
