### PR TITLE
Upgrade web assets

### PR DESCRIPTION
**Pull request by TylerVigario**
Finally got around to upgrading WebPack to v5, along with some other improvements.

I have not tested.

### CODE REVIEW

**Comment by TerryGeng** [comment]
Great! I have skimmed through and thought the new limitChar function can be a solution of #148. What's your thought about it?

**Comment by TylerVigario** [comment]
I agree. That would help ease the issue.

**Comment by azlux** [comment]
Are we ready to merge ?

**Comment by TylerVigario** [comment]
I have not tested it, but it should be good.

**Comment by TerryGeng** [comment]
Sorry for having kept you waiting for so long. Today I tried to test this PR can get it merged. After the normal compile process, I see the exception in my debug console and the page can not be loaded properly.
```
Uncaught ReferenceError: define is not defined
    at Object.4002 (jquery.js:1)
    at t (bootstrap:18)
    at main.js:2
    at main.js:2
    at main.js:2
```

Which points to this guy here:
image

I think this could be some import error in webpack or something else. Can you have a look at it?

**Comment by TylerVigario** [comment]
My apologies I hoped all would be well. I'll take some time to properly test and resolve all issues.

**Comment by TylerVigario** [comment]
Corrected.

**Comment by TylerVigario** [comment]
As a bonus, I went through the HTML and compiled a list of used icons. I've subset the Font Awesome icons to only include the ones used.

**Comment by TylerVigario** [comment]
I've tested this, and it is ready to merge.

**Comment by TerryGeng** [comment]
Great work! I have noticed a significant size reduction of the output main.js file. This is amazing and huge thanks for you.

I have tested it and it works gorgeously. Let's get this PR merged.

**Pull request merged**
