### PR TITLE
Bot: TRADUORA Update

### PR DESCRIPTION
**Pull request by azlux**

### CODE REVIEW

**Comment by TerryGeng** [comment]
@felix91gr @Gunzinger @azlux Can you help with the new strings added in #186?

It involves a new string called "Position" to indicate the position of a song in the playlist.
Combining with other strings, it can be "Position: Next song." or "Position: Last one on the queue."

**Comment by felix91gr** [comment]
@TerryGeng sure! Although I can't see any of those strings in the Traduora project, are you sure that the english source is being uploaded?

**Comment by felix91gr** [comment]
Maybe you mean that after this gets merged, we come in and translate them in the webpage? :)

**Comment by TerryGeng** [comment]
@felix91gr They are `position_in_the_queue`, `next_to_play` and `last_song_on_the_queue`. Can you try a search in traduora?

**Comment by felix91gr** [comment]
Ahhhh, okay, yas. I have translated those already ^^

**Comment by azlux** [comment]
Ok, the bot is working again.

**Comment by azlux** [comment]
I'm merging this PR.

**Comment by felix91gr** [comment]
⛵️

**Pull request merged**
