### PR TITLE
Cleanup artifacts from node build flow

### PR DESCRIPTION
**Pull request by TylerVigario**
I've removed the unused `scripts` folder and simplified the directories a bit.

I also added the NPM steps for building the web interface to the install instructions. This may need to be added to other places as well as come with a disclaimer that it's only for web interface functionality.

### CODE REVIEW

**Comment by TerryGeng** [comment]
Thanks. Merged!

**Comment by felix91gr** [comment]
@TylerVigario I was wondering why my `master`-following bot had no css this week XD

I guess I need to make a bot to watch the `README.md` for changes as well, so that I stay informed in case something changes in the installation instructions :3

Regarding that, I have a question: we don't have `npm` installed in our server. What are the best steps for installing it? 

I tend to like solutions like `venv` for python (which doesn't touch the global namespace). I have also used such a thing for Ruby (rbenv I think?) and it was nice to know that even if I broke something in my local copy of the project, nothing would break in any of my other environments. Is there such a thing in the JS + Node world?

**Comment by felix91gr** [comment]
Another thing: I've been able to see the web interface, even though I don't have Node installed. The CSS and JS aren't there (they give 404) but the HTML and images are loading. Is that okay? Maybe Flask is serving me the webpage? Should Flask still be running?

@TylerVigario

**Comment by TylerVigario** [comment]
NPM by default will install only within the current project scope. To install packages globally you must add `-g`.

**Comment by felix91gr** [comment]
> NPM by default will install only within the current project scope. To install packages globally you must add -g.

Niiiice. :3

Btw, I'm in Ubuntu. should I install NPM from the 18.04 `apt-get` repositories, or should I add a custom PPA? How did you install your NPM?

**Comment by azlux** [comment]
@felix91gr I'm working to have a master without git with all css/js compiled for every commit.
You can see there already are a target version https://github.com/azlux/botamusique/blob/master/configuration.default.ini#L41 named testing

**Comment by TylerVigario** [comment]
@felix91gr I get the latest Node on Linux from https://github.com/nodesource/distributions

**Comment by felix91gr** [comment]
> I'm working to have a master without git with all css/js compiled for every commit.

@azlux what do you mean?

> I get the latest Node on Linux from https://github.com/nodesource/distributions

@TylerVigario thanks! :)

**Comment by TylerVigario** [comment]
@felix91gr I believe he is referring to an automatic packaged release based on master that will include the compiled web assets. It would remove the requirement of having to compile the web assets yourself with each commit.

**Comment by felix91gr** [comment]
Ohh, that's nice! :)

**Comment by TerryGeng** [comment]
I think I can write a procedure to ensure the web interface will only work when the js and css are compiled i.e. check if the main.js and custom.css exist. What do you think about this?

**Comment by TylerVigario** [comment]
Might be better to display a helpful error.

**Comment by felix91gr** [comment]
Ohh, that would be sweet!

**Comment by felix91gr** [comment]
I think I prefer the helpful error, sorta like a landing page linking to the instructions or something like that. Depends on how much hassle that would mean maybe :thinking:

**Pull request merged**
